spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://config-server:11009/"
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY