spring:
  application:
    name: mongo-service
  config:
    import: "optional:configserver:http://config-server:11009"
  jwt:
    secret: "5v8VrmHq93E/5Dg9lT10pQWmXz2yYkJr1s3H6z8aG0k="
    expiration: 86400
  logging:
    level:
      ROOT: WARN
      com.microservice.mongo: INFO, DEBUG