server:
  port: 11009

spring:
  application:
    name: configServer
  profiles:
    active: native
  output:
    ansi:
      enabled: always
  cloud:
    config:
      server:
        #        git:
        #          uri: https://github.com/nghiabeoniamey/microservices-config-server
        native:
          search-locations: classpath:/config
        encrypt:
          enabled: false
        bootstrap: true
      allow-override: true
logging:
  level:
    root: info
    com.microservice: debug
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"
